#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

echo 'Antoxx in bash';

read -n 1 -p "Need to build app [y/n]: " AMSURE
[ "$AMSURE" = "y" ] || exit
echo "" 1>&2
echo ls;

unlink $OPENSHIFT_REPO_DIR/php/index.php;
ln -s $OPENSHIFT_REPO_DIR/web/app_dev.php $OPENSHIFT_REPO_DIR/php/index.php